### ISSUE TITLE
Summary length too long for upcoming Elm 0.19.1

### ISSUE THREAD

**Issue by andys8** [r-k-b/elm-interval#7]
Hey,

there will be a change, where the summary of a package is [checked in byte length](https://github.com/elm/compiler/commit/2bcebaf4ab3517abcfaaeffa66da9f2d347521e4).

The summary of this package will then be too long and fail to compile. Also for people who are using the package.

https://github.com/r-k-b/elm-interval/blob/a7f5f8a9b4e44d6c5b2e8c11d743ce791c3c8514/elm.json#L4

Would be great if you could change it and republish the package :)

By the way, I used a script to find all non-compiling packages to make sure upcoming Elm release will work well with existing packages: https://github.com/andys8/elm-compiler-test :)

**Comment by r-k-b** [comment]
Thanks Andy.
Hopefully [this site](https://mothereff.in/byte-counter) counts bytes the same way the updated compiler will...
